CREATE TABLE IF NOT EXISTS jira_credentials (
  id INTEGER PRIMARY KEY DEFAULT 1,
  email VARCHAR(255) NOT NULL,
  api_token TEXT NOT NULL,
  domain VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT single_row CHECK (id = 1)
);
